import { expect,test } from '@playwright/test'
import { translate,type Locale } from '../src/i18n/index.js'
test('collapses, retains navigation and saves the desktop preference',async({page},info)=>{
  const L=(key:string)=>translate(key,info.project.name as Locale)
  await page.route('**/api/**',route=>{
    const path=new URL(route.request().url()).pathname
    if(path.endsWith('/get-session'))return route.fulfill({json:{user:{id:'owner',name:'Owner',email:'owner@example.test'}}})
    if(path.endsWith('/organizations'))return route.fulfill({json:[{id:'org',name:'Workspace',role:'owner'}]})
    if(path.endsWith('/projects'))return route.fulfill({json:[{id:'project',name:'Active project'}]})
    if(path.endsWith('/reports/summary'))return route.fulfill({json:{cards:[],jobs:[],runs:[],cost:{status:'unavailable'}}})
    if(path.endsWith('/events'))return route.fulfill({contentType:'text/event-stream',body:': ready\n\n'})
    return route.fulfill({json:[]})
  })
  await page.goto('/')
  await expect(page.locator('.page-project-context')).toContainText('Active project')
  await page.getByRole('button',{name:L('Close sidebar'),exact:true}).click()
  await expect(page.locator('.workspace-shell')).toHaveClass(/sidebar-collapsed/)
  const reports=page.getByRole('navigation').getByRole('button',{name:L('Reports'),exact:true})
  await reports.focus()
  await expect(page.getByRole('tooltip')).toHaveText(L('Reports'))
  await reports.click()
  await expect(page.locator('h1')).toHaveText(L('Reports'))
  await expect(page.locator('.page-project-context')).toContainText('Active project')
  await page.reload()
  await expect(page.locator('.workspace-shell')).toHaveClass(/sidebar-collapsed/)
  await page.getByRole('button',{name:L('Open sidebar'),exact:true}).click()
  await expect(page.getByRole('combobox',{name:L('Project'),exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:844})
  await expect(page.locator('.workspace-shell')).toHaveClass(/sidebar-collapsed/)
  await page.getByRole('button',{name:L('Open sidebar'),exact:true}).click()
  await expect(page.locator('.workspace-shell')).toHaveClass(/sidebar-mobile-open/)
  await page.getByRole('navigation').getByRole('button',{name:L('Reports'),exact:true}).click()
  await expect(page.locator('.workspace-shell')).not.toHaveClass(/sidebar-mobile-open/)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
